version: "3"
services:


 rabbit-1:
   image: kuznero/rabbitmq:3.6.6-cluster
   environment:
     - RABBITMQ_SETUP_DELAY=120
     - RABBITMQ_USER=admin
     - RABBITMQ_PASSWORD=adminpwd
     - RABBITMQ_CLUSTER_NODES='rabbit@rabbit-2 rabbit@rabbit'
     - RABBITMQ_NODENAME=rabbit@rabbit-1
     - RABBITMQ_ERLANG_COOKIE=a-little-secret
     - RABBITMQ_FIREHOSE_QUEUENAME=trace
     - RABBITMQ_FIREHOSE_ROUTINGKEY=publish.#
   networks:
     - net
   volumes:
     - /data/rabbitmq-1:/var/lib/rabbitmq
   deploy:
     placement:
       constraints: [node.labels.rabbitmq==1]

 rabbit-2:
   image: kuznero/rabbitmq:3.6.6-cluster
   environment:
     - RABBITMQ_SETUP_DELAY=60
     - RABBITMQ_USER=admin
     - RABBITMQ_PASSWORD=adminpwd
     - RABBITMQ_CLUSTER_NODES='rabbit@rabbit-1 rabbit@rabbit'
     - RABBITMQ_NODENAME=rabbit@rabbit-2
     - RABBITMQ_ERLANG_COOKIE=a-little-secret
     - RABBITMQ_FIREHOSE_QUEUENAME=trace
     - RABBITMQ_FIREHOSE_ROUTINGKEY=publish.#
   networks:
     - net
   volumes:
     - /data/rabbitmq-2:/var/lib/rabbitmq
   deploy:
     placement:
       constraints: [node.labels.rabbitmq==2]

  rabbit:
    image: kuznero/rabbitmq:3.6.6-cluster
    environment:
      - RABBITMQ_SETUP_DELAY=20
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=adminpwd
      - RABBITMQ_CLUSTER_NODES='rabbit@rabbit-1 rabbit@rabbit-2'
      - RABBITMQ_NODENAME=rabbit@rabbit
      - RABBITMQ_ERLANG_COOKIE=a-little-secret
      - RABBITMQ_FIREHOSE_QUEUENAME=trace
      - RABBITMQ_FIREHOSE_ROUTINGKEY=publish.#
    ports:
      - 15672:15672    
    networks:
      - net
    volumes:
      - /data/rabbitmq-3:/var/lib/rabbitmq
    deploy:
      placement:
        constraints: [node.labels.rabbitmq==3]
